### ISSUE TITLE
Todo gift & F&F 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6883]
- [x] Modal should appear properly in both cases

- [x] Users can feed OTP / number and proceed

- [x] After accepting or rejecting proper toast message or notification

**Comment by Deveshshankar** [comment]
Will test once refresh works

**Comment by Deveshshankar** [comment]
https://xd.adobe.com/view/f11ee4be-fef5-4c9b-9e22-4ae72872c584-a44d/screen/f580a96b-4287-4973-b38b-7263ac5e0805/

**Comment by Deveshshankar** [comment]
Completed
